TTT:
  script:
    - wget http://www.sourcemod.net/smdrop/1.8/sourcemod-1.8.0-git5711-linux.tar.gz
    - tar xzf sourcemod-1.8.0-git5711-linux.tar.gz
    - cd addons/sourcemod/scripting
    - chmod +x spcomp
    - ./spcomp ttt.sp
    - ./spcomp crashcatcher.sp
    - ls *.smx